export interface Invoice {
  Type: string;
  recordid: string;
  PartyName: string;
  Currency: string;
  PayeeFinancialAccount: string;
  InvoiceLabel: string; // Its really an array but is not parsed
  PayableAmount: number;
  DueDate: string;
  FullUsername: string;
  Status: string;
  TransactionType: "Income" | "Outcome";
}

export function formatInvoice(invoice: Invoice) {
  const summary = `Invoice ${Math.round(invoice.PayableAmount)} ${
    invoice.Currency
  } for: ${invoice.PartyName}`;

  const description =
    "<div>Generated by" +
    invoice.FullUsername +
    "<br/><ul><li>PayeeFinancialAccount: " +
    invoice.PayeeFinancialAccount +
    "</li><li>InvoiceLabel: " +
    JSON.parse(invoice.InvoiceLabel)[0] +
    "</li></ul></div>";

  const colorId = 4; // red

  return {
    summary,
    colorId,
    description,
    start: {
      date: invoice.DueDate
    },
    end: {
      date: invoice.DueDate
    }
  };
}
